version: "3.7"

services:
    valheim:
        container_name: faulo-valheim        
        image: faulo/valheim:latest
        build:
            context: .
            dockerfile: Dockerfile
        privileged: true
        user: root
        entrypoint: start_server_env.sh
